name: SudokuSolver
version: 0.1.0.0
github: "a-churchill/SudokuSolver"
license: BSD3
author: "Andrew Churchill"
maintainer: "chu.andrew.8@outlook.com"
copyright: "2020 Andrew Churchill"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/a-churchill/SudokuSolver#readme>

dependencies:
  - base >= 4.7 && < 5
  - containers
  - QuickCheck
  - hspec

library:
  source-dirs: src

executables:
  SudokuSolver-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - SudokuSolver

tests:
  SudokuSolver-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - SudokuSolver
